# -*- coding: utf-8 -*-
"""Copy of Hackaton.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X4-aD4zs97_fJSHLaabiz89uSNeqoTlk
"""

import pandas as pd 

data = pd.read_csv("train.csv", delimiter=",")

columns_with_na_bed_grade = data[pd.isna(data['Bed.Grade'])]
len(columns_with_na_bed_grade)

columns_with_na_city_code_patient = data[pd.isna(data['City_Code_Patient'])]

patient_id_na_city_code_patient = columns_with_na_city_code_patient['patientid']

patient_id_na_city_code_patient = list(set(patient_id_na_city_code_patient))

print("Cantidad de rows con na en city_code_patient {}, univocas: {}".format(len(columns_with_na_city_code_patient), len(patient_id_na_city_code_patient)))

duplicated_patients_with_na_code_patient = []

for patientid in patient_id_na_city_code_patient:
  amount = 0
  for value in data['patientid'] == patientid:
    if value:
      amount = amount + 1
  if amount > 1:
    duplicated_patients_with_na_code_patient.append(patientid)
    

for patient_id in duplicated_patients_with_na_code_patient:   
  for row in zip(data['patientid'],data['City_Code_Patient']):
    if (patient_id == row[0]) and (not pd.isna(row[1])):
      print('Encontré un paciente que en un lado tiene NA en city code patient, y en otro no. PatientID: {}'.format(patientid))
      break

#
